# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'T1.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QTime, QDate,Qt
from test4_2 import Ui_Form


class Ui_MainWindow(QtWidgets.QWidget):


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(858, 534)
        MainWindow.setStyleSheet("background-color:rgb(0, 0, 50)")

        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Heightl = QtWidgets.QLabel(self.centralwidget)
        self.Heightl.setGeometry(QtCore.QRect(430, 70, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Heightl.setFont(font)
        self.Heightl.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-top-color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 50);\n"
"border-radius:10px")
        self.Heightl.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Heightl.setObjectName("Heightl")
        self.Weightl = QtWidgets.QLabel(self.centralwidget)
        self.Weightl.setGeometry(QtCore.QRect(430, 140, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Weightl.setFont(font)
        self.Weightl.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 50);\n"
"border-radius:10px")
        self.Weightl.setObjectName("Weightl")
        self.Radiusl = QtWidgets.QLabel(self.centralwidget)
        self.Radiusl.setGeometry(QtCore.QRect(430, 210, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Radiusl.setFont(font)
        self.Radiusl.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 50);\n"
"border-radius:10px")
        self.Radiusl.setObjectName("Radiusl")
        self.He_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.He_lineEdit.setGeometry(QtCore.QRect(580, 70, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.He_lineEdit.setFont(font)
        self.He_lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color:rgb(85, 85, 255);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-radius:10px;")
        self.He_lineEdit.setObjectName("He_lineEdit")
        self.We_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.We_lineEdit.setGeometry(QtCore.QRect(580, 140, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.We_lineEdit.setFont(font)
        self.We_lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color:rgb(85, 85, 255);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-radius:10px")
        self.We_lineEdit.setObjectName("We_lineEdit")
        self.Ra_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Ra_lineEdit.setGeometry(QtCore.QRect(580, 210, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.Ra_lineEdit.setFont(font)
        self.Ra_lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color:rgb(85, 85, 255);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-radius:10px")
        self.Ra_lineEdit.setObjectName("Ra_lineEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 350, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 50);\n"
"border-radius:10px")
        self.label.setObjectName("label")
        self.Maleb = QtWidgets.QRadioButton(self.centralwidget)
        self.Maleb.setGeometry(QtCore.QRect(590, 280, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.Maleb.setFont(font)
        self.Maleb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Maleb.setStyleSheet("color: rgb(255, 255, 255);")
        self.Maleb.setObjectName("Maleb")
        self.Femaleb = QtWidgets.QRadioButton(self.centralwidget)
        self.Femaleb.setGeometry(QtCore.QRect(720, 280, 101, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.Femaleb.setFont(font)
        self.Femaleb.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Femaleb.setStyleSheet("color: rgb(255, 255, 255);")
        self.Femaleb.setObjectName("Femaleb")
        self.We_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.We_comboBox.setGeometry(QtCore.QRect(750, 140, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.We_comboBox.setFont(font)
        self.We_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.We_comboBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 90);\n"
"border-color: rgb(85, 85, 255);\n"
"border-width:1px;\n"
"border-radius:10px;\n"
"border-style: solid;\n"
"")
        self.We_comboBox.setObjectName("We_comboBox")
        self.We_comboBox.addItem("")
        self.We_comboBox.addItem("")
        self.He_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.He_comboBox.setGeometry(QtCore.QRect(750, 70, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.He_comboBox.setFont(font)
        self.He_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.He_comboBox.setStyleSheet("color:  rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 90);\n"
"border-color: rgb(85, 85, 255);\n"
"border-width:1px;\n"
"border-radius:10px;\n"
"border-style: solid;")
        self.He_comboBox.setEditable(False)
        self.He_comboBox.setObjectName("He_comboBox")
        self.He_comboBox.addItem("")
        self.He_comboBox.addItem("")
        self.Ra_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Ra_comboBox.setGeometry(QtCore.QRect(750, 210, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.Ra_comboBox.setFont(font)
        self.Ra_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Ra_comboBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(85, 85, 255);\n"
"border-width:1px;\n"
"border-radius:10px;\n"
"border-style: solid;\n"
"")
        self.Ra_comboBox.setFrame(False)
        self.Ra_comboBox.setObjectName("Ra_comboBox")
        self.Ra_comboBox.addItem("")
        self.Ra_comboBox.addItem("")
        self.Ra_comboBox.addItem("")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(500, 450, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton1.setFont(font)
        self.pushButton1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1.setAutoFillBackground(False)
        self.pushButton1.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(232, 232, 0);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-radius:15px")
        self.pushButton1.setObjectName("pushButton1")
        self.Wishl = QtWidgets.QLabel(self.centralwidget)
        self.Wishl.setGeometry(QtCore.QRect(430, 280, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei Light")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.Wishl.setFont(font)
        self.Wishl.setStyleSheet("color: rgb(255, 255, 255);\n"
"background-color:rgb(0, 0, 50);\n"
"border-radius:10px")
        self.Wishl.setObjectName("Wishl")
        self.Wi_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Wi_lineEdit.setGeometry(QtCore.QRect(580, 350, 151, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.Wi_lineEdit.setFont(font)
        self.Wi_lineEdit.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color:rgb(85, 85, 255);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-radius:10px")
        self.Wi_lineEdit.setObjectName("Wi_lineEdit")
        self.Wi_comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.Wi_comboBox.setGeometry(QtCore.QRect(750, 350, 91, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(16)
        self.Wi_comboBox.setFont(font)
        self.Wi_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.Wi_comboBox.setStyleSheet("color: rgb(255, 255, 255);\n"
"alternate-background-color: rgb(0, 0, 90);\n"
"border-color: rgb(85, 85, 255);\n"
"border-width:1px;\n"
"border-radius:10px;\n"
"border-style: solid;")
        self.Wi_comboBox.setFrame(False)
        self.Wi_comboBox.setObjectName("Wi_comboBox")
        self.Wi_comboBox.addItem("")
        self.Wi_comboBox.addItem("")
        self.Wi_comboBox.addItem("")
        self.pushButton1_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1_2.setGeometry(QtCore.QRect(690, 450, 141, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        self.pushButton1_2.setFont(font)
        self.pushButton1_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton1_2.setAutoFillBackground(False)
        self.pushButton1_2.setStyleSheet("color: rgb(255, 255, 255);\n"
"border-color: rgb(255, 0, 0);\n"
"border-width:2px;\n"
"border-style:solid;\n"
"border-radius:15px")
        self.pushButton1_2.setObjectName("pushButton1_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(0, 40, 481, 501))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("photos/356-3569471_treadmill-png-transparent-images-cybex-770t-treadmill-clipart.png"))
        self.label_2.setScaledContents(True)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(20, 20, 221, 71))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(35)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color:rgb(255, 11, 11)")
        self.label_3.setObjectName("label_3")
        self.label_2.raise_()
        self.Wishl.raise_()
        self.Weightl.raise_()
        self.Radiusl.raise_()
        self.label.raise_()
        self.Heightl.raise_()
        self.Ra_lineEdit.raise_()
        self.Ra_comboBox.raise_()
        self.Femaleb.raise_()
        self.He_lineEdit.raise_()
        self.Wi_lineEdit.raise_()
        self.Maleb.raise_()
        self.Wi_comboBox.raise_()
        self.We_comboBox.raise_()
        self.We_lineEdit.raise_()
        self.He_comboBox.raise_()
        self.pushButton1.raise_()
        self.pushButton1_2.raise_()
        self.label_3.raise_()
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



        self.pushButton1.clicked.connect(self.calculate)


    height = 0.0
    weight = 0.0
    radius = 0.0
    goal = 0.0



    def calculate(self):
        height = self.He_lineEdit.text()
        weight = self.We_lineEdit.text()
        radius = self.Ra_lineEdit.text()
        goal = self.Wi_lineEdit.text()

        print(height,weight,radius,goal)



    def openWindow(self):
        self.Form = QtWidgets.QWidget()
        self.ui = Ui_Form()
        self.ui.setupUi(self.Form)
        self.Form.show()
        MainWindow.hide()



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Heightl.setText(_translate("MainWindow", "<html><head/><body><p>Height</p></body></html>"))
        self.Weightl.setText(_translate("MainWindow", "<html><head/><body><p>Weight</p></body></html>"))
        self.Radiusl.setText(_translate("MainWindow", "<html><head/><body><p>Radius</p></body></html>"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p>Your goal</p></body></html>"))
        self.Maleb.setText(_translate("MainWindow", "Male"))
        self.Femaleb.setText(_translate("MainWindow", "Female"))
        self.We_comboBox.setItemText(0, _translate("MainWindow", "kg"))
        self.We_comboBox.setItemText(1, _translate("MainWindow", "lb"))
        self.He_comboBox.setItemText(0, _translate("MainWindow", "m"))
        self.He_comboBox.setItemText(1, _translate("MainWindow", "inch"))
        self.Ra_comboBox.setItemText(0, _translate("MainWindow", "cm"))
        self.Ra_comboBox.setItemText(1, _translate("MainWindow", "mm"))
        self.Ra_comboBox.setItemText(2, _translate("MainWindow", "default"))
        self.pushButton1.setText(_translate("MainWindow", "Enter"))
        self.Wishl.setText(_translate("MainWindow", "<html><head/><body><p>Gender</p></body></html>"))
        self.Wi_comboBox.setItemText(0, _translate("MainWindow", "m"))
        self.Wi_comboBox.setItemText(1, _translate("MainWindow", "km"))
        self.Wi_comboBox.setItemText(2, _translate("MainWindow", "mil"))
        self.pushButton1_2.setText(_translate("MainWindow", "Close"))
        self.label_3.setText(_translate("MainWindow", "Treadmill"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
