# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, QtMultimedia
from PyQt5.QtCore import QTimer, QTime, QDate, Qt
from PyQt5.QtWidgets import QMessageBox, QInputDialog, QFileDialog
import sys


class Ui_Form(QtWidgets.QWidget, QtCore.QTimer):


    def setupUi(self, Form):


        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1150, 892)
        Form.setWindowFlag(Qt.FramelessWindowHint)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())

        Form.setSizePolicy(sizePolicy)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.011, stop:0.0227273 rgba(0, 0, 28, 255), stop:0.977273 rgba(0, 0, 39, 255))")
        
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(880, 170, 241, 131))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.label_time = QtWidgets.QLabel(self.frame)
        self.label_time.setGeometry(QtCore.QRect(50, 60, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 41, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("photos/79-795942_or-tool-svg-png-icon-free-download-clock.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 181, 41))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(880, 330, 241, 151))
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 51, 51))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("photos/Calories_Burned_-fire-Calories_Burn-Burn-Metabolism-512.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 111, 41))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        
        self.label_calories = QtWidgets.QLabel(self.frame_2)
        self.label_calories.setGeometry(QtCore.QRect(80, 60, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(48)
        self.label_calories.setFont(font)
        self.label_calories.setObjectName("label_calories")
        
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(30, 340, 371, 131))
        self.frame_3.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        
        self.label_distance = QtWidgets.QLabel(self.frame_3)
        self.label_distance.setGeometry(QtCore.QRect(190, 60, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_distance.setFont(font)
        self.label_distance.setTextFormat(QtCore.Qt.RichText)
        self.label_distance.setObjectName("label_distance")
        
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(0, -10, 191, 141))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("photos/road-icon-on-white-background-vector-21154187.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(210, 20, 111, 41))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(290, 60, 61, 51))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(30, 500, 371, 131))
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(100, 20, 71, 41))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("photos/600-6003521_ketond-keto-supplements-com-agility-icon-png-transparent.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(180, 70, 91, 51))
        self.label_6.setObjectName("label_6")
        
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(170, 20, 91, 41))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        
        self.label_speed = QtWidgets.QLabel(self.frame_4)
        self.label_speed.setGeometry(QtCore.QRect(100, 70, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        self.label_speed.setFont(font)
        self.label_speed.setTextFormat(QtCore.Qt.RichText)
        self.label_speed.setObjectName("label_speed")
        
        self.pushButton_speed_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_speed_2.setGeometry(QtCore.QRect(290, 70, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_speed_2.setFont(font)
        self.pushButton_speed_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_speed_2.setStyleSheet("color: rgb(255, 255, 0);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(255, 255, 0);\n"
"border-radius: 25px;")
        self.pushButton_speed_2.setObjectName("pushButton_speed_2")
        
        self.pushButton_speed_1 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_speed_1.setGeometry(QtCore.QRect(20, 70, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_speed_1.setFont(font)
        self.pushButton_speed_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_speed_1.setStyleSheet("color: rgb(255, 255, 0);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(255, 255, 0);\n"
"border-radius: 25px;")
        self.pushButton_speed_1.setObjectName("pushButton_speed_1")
        
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(320, 810, 241, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_start.setStyleSheet("color: white;\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(165, 0, 0);\n"
"border-radius: 20px;")
        self.pushButton_start.setObjectName("pushButton_start")
        
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setGeometry(QtCore.QRect(580, 810, 241, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop.setStyleSheet("color: white;\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color:rgb(255, 255, 0) ;\n"
"border-radius: 20px;")
        self.pushButton_stop.setObjectName("pushButton_stop")
        
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(430, 170, 421, 461))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setPixmap(QtGui.QPixmap("photos/source (1).gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(40, 10, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: white;")
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName("label_12")
        
        
        self.pushButton_setting_2 = QtWidgets.QPushButton(Form)
        self.pushButton_setting_2.setGeometry(QtCore.QRect(1000, 20, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_setting_2.setFont(font)
        self.pushButton_setting_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_setting_2.setStyleSheet("border-width: 4px;\n"
"border-style: solid;\n"
"border-radius: 25px;")
        self.pushButton_setting_2.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photos/Minus.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting_2.setIcon(icon)
        self.pushButton_setting_2.setIconSize(QtCore.QSize(61, 61))
        self.pushButton_setting_2.setObjectName("pushButton_setting_2")
        self.pushButton_setting_2.setToolTip("minimize")



        self.pushButton_setting_7 = QtWidgets.QPushButton(Form)
        self.pushButton_setting_7.setGeometry(QtCore.QRect(140, 810, 71, 61))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_setting_7.setFont(font)
        self.pushButton_setting_7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_setting_7.setStyleSheet("border-width: 3px;\n"
"border-style: solid;\n"
"border-radius: 30px;")
        self.pushButton_setting_7.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photos/video-player1.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting_7.setIcon(icon)
        self.pushButton_setting_7.setIconSize(QtCore.QSize(56, 56))
        self.pushButton_setting_7.setObjectName("pushButton_setting_7")
        self.pushButton_setting_7.setToolTip("next")



        
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(60, 40, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: white;")
        self.label_13.setObjectName("label_13")
        
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(30, 170, 371, 141))
        self.frame_5.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(140, 10, 201, 41))
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        
        self.label_steps = QtWidgets.QLabel(self.frame_5)
        self.label_steps.setGeometry(QtCore.QRect(200, 50, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.label_steps.setFont(font)
        self.label_steps.setObjectName("label_steps")
        
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(20, 20, 111, 111))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("photos/feet-clipart-blue-foot-foot-icon-png-transparent.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(30, 90, 1101, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        self.progressBar.setFont(font)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 50);\n"
"border: 3px solid ;\n"
"border-color: rgb(0, 0, 50)")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setGeometry(QtCore.QRect(1070, 20, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("border-width: 4px;\n"
"border-style: solid;\n"
"border-radius: 25px;")
        self.pushButton_exit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("photos/close.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exit.setIcon(icon1)
        self.pushButton_exit.setIconSize(QtCore.QSize(56, 56))
        self.pushButton_exit.setObjectName("pushButton_exit")
        self.pushButton_exit.setToolTip("close")

        
        self.pushButton_setting_3 = QtWidgets.QPushButton(Form)
        self.pushButton_setting_3.setGeometry(QtCore.QRect(20, 810, 61, 61))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_setting_3.setFont(font)
        self.pushButton_setting_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_setting_3.setStyleSheet("border-width: 3px;\n"
"border-style: solid;\n"
"border-radius: 30px;")
        self.pushButton_setting_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("photos/video-player2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting_3.setIcon(icon2)
        self.pushButton_setting_3.setIconSize(QtCore.QSize(52, 52))
        self.pushButton_setting_3.setObjectName("pushButton_setting_3")
        self.pushButton_setting_3.setToolTip("previous")

        
        self.pushButton_setting_4 = QtWidgets.QPushButton(Form)
        self.pushButton_setting_4.setGeometry(QtCore.QRect(80, 810, 61, 61))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_setting_4.setFont(font)
        self.pushButton_setting_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_setting_4.setStyleSheet("border-width: 3px;\n"
"border-style: solid;\n"
"border-radius: 30px;")
        self.pushButton_setting_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("photos/video-player.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting_4.setIcon(icon3)
        self.pushButton_setting_4.setIconSize(QtCore.QSize(69, 69))
        self.pushButton_setting_4.setObjectName("pushButton_setting_4")
        self.pushButton_setting_4.setToolTip("play/pause")
        
        self.frame_6 = QtWidgets.QFrame(Form)
        self.frame_6.setGeometry(QtCore.QRect(30, 660, 371, 131))
        self.frame_6.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        
        self.label_16 = QtWidgets.QLabel(self.frame_6)
        self.label_16.setGeometry(QtCore.QRect(160, 10, 201, 41))
        self.label_16.setStyleSheet("")
        self.label_16.setObjectName("label_16")
        
        self.label_25 = QtWidgets.QLabel(self.frame_6)
        self.label_25.setGeometry(QtCore.QRect(30, 0, 131, 141))
        self.label_25.setText("")
        self.label_25.setPixmap(QtGui.QPixmap("photos/man-tall-scale-icon-vector-260nw-733383220.png"))
        self.label_25.setScaledContents(True)
        self.label_25.setObjectName("label_25")
        
        self.lineEdit = QtWidgets.QLineEdit(self.frame_6)
        self.lineEdit.setGeometry(QtCore.QRect(190, 60, 71, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 50);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color:  rgb(0, 0, 50);\n"
"")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setValidator(QtGui.QDoubleValidator())
        
        self.comboBox = QtWidgets.QComboBox(self.frame_6)
        self.comboBox.setGeometry(QtCore.QRect(270, 60, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.comboBox.setFont(font)
        self.comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox.setStyleSheet("color: white;\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color:  rgb(0, 0, 113);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 113);")
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        
        self.label_17 = QtWidgets.QLabel(self.frame_6)
        self.label_17.setGeometry(QtCore.QRect(180, 90, 91, 20))
        self.label_17.setStyleSheet("color: white ;")
        self.label_17.setObjectName("label_17")
        
        self.label_16.raise_()
        self.label_25.raise_()
        self.label_17.raise_()
        self.lineEdit.raise_()
        self.comboBox.raise_()
        
        self.frame_7 = QtWidgets.QFrame(Form)
        self.frame_7.setGeometry(QtCore.QRect(430, 660, 421, 131))
        self.frame_7.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_7.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        
        self.label_18 = QtWidgets.QLabel(self.frame_7)
        self.label_18.setGeometry(QtCore.QRect(170, 10, 201, 41))
        self.label_18.setStyleSheet("")
        self.label_18.setObjectName("label_18")
        
        self.label_26 = QtWidgets.QLabel(self.frame_7)
        self.label_26.setGeometry(QtCore.QRect(40, 10, 121, 111))
        self.label_26.setText("")
        self.label_26.setPixmap(QtGui.QPixmap("photos/scales-for-measuring-weight-a-human-icon-vector-9901352.png"))
        self.label_26.setScaledContents(True)
        self.label_26.setObjectName("label_26")
        
        self.lineEdit_2 = QtWidgets.QLineEdit(self.frame_7)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 60, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 50);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color:  rgb(0, 0, 50);\n"
"")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setValidator(QtGui.QDoubleValidator())
        
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_7)
        self.comboBox_2.setGeometry(QtCore.QRect(290, 60, 81, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.comboBox_2.setFont(font)
        self.comboBox_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_2.setStyleSheet("color: white;\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color:  rgb(0, 0, 113);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 113);")
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        
        self.label_19 = QtWidgets.QLabel(self.frame_7)
        self.label_19.setGeometry(QtCore.QRect(190, 90, 101, 20))
        self.label_19.setStyleSheet("color: white ;")
        self.label_19.setObjectName("label_19")
        self.label_18.raise_()
        self.label_26.raise_()
        self.label_19.raise_()
        self.lineEdit_2.raise_()
        self.comboBox_2.raise_()
        
        self.frame_8 = QtWidgets.QFrame(Form)
        self.frame_8.setGeometry(QtCore.QRect(880, 510, 241, 131))
        self.frame_8.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_8.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        
        self.label_20 = QtWidgets.QLabel(self.frame_8)
        self.label_20.setGeometry(QtCore.QRect(10, 20, 81, 81))
        self.label_20.setStyleSheet("border-width: 1px;\n"
"border-style: solid;\n"
"border-color:rgb(0, 0, 50) ;")
        self.label_20.setText("")
        self.label_20.setPixmap(QtGui.QPixmap("photos/Screenshot (88).png"))
        self.label_20.setScaledContents(True)
        self.label_20.setObjectName("label_20")
        
        self.label_21 = QtWidgets.QLabel(self.frame_8)
        self.label_21.setGeometry(QtCore.QRect(110, 20, 111, 41))
        self.label_21.setStyleSheet("")
        self.label_21.setObjectName("label_21")
        
        self.comboBox_3 = QtWidgets.QComboBox(self.frame_8)
        self.comboBox_3.setGeometry(QtCore.QRect(170, 60, 61, 41))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.comboBox_3.setFont(font)
        self.comboBox_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_3.setStyleSheet("color: white;\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color:  rgb(0, 0, 113);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 113);")
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        
        self.label_22 = QtWidgets.QLabel(self.frame_8)
        self.label_22.setGeometry(QtCore.QRect(80, 90, 91, 20))
        self.label_22.setStyleSheet("color: white ;")
        self.label_22.setObjectName("label_22")
        
        self.lineEdit_3 = QtWidgets.QLineEdit(self.frame_8)
        self.lineEdit_3.setGeometry(QtCore.QRect(90, 60, 81, 41))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        self.lineEdit_3.setFont(font)
        self.lineEdit_3.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 50);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color:  rgb(0, 0, 50);\n"
"")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setValidator(QtGui.QDoubleValidator())
        
        self.label_20.raise_()
        self.label_22.raise_()
        self.label_21.raise_()
        self.comboBox_3.raise_()
        self.lineEdit_3.raise_()
        
        self.frame_9 = QtWidgets.QFrame(Form)
        self.frame_9.setGeometry(QtCore.QRect(880, 670, 241, 121))
        self.frame_9.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_9.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        
        self.pushButton_setting_5 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_setting_5.setGeometry(QtCore.QRect(30, 30, 81, 81))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_setting_5.setFont(font)
        self.pushButton_setting_5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_setting_5.setStyleSheet("border-width: 6px;\n"
"border-style: solid;\n"
"border-radius: 40px;\n"
"border-color: black;\n"
"\n"
"")
        self.pushButton_setting_5.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap("photos/user_male2-512.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting_5.setIcon(icon4)
        self.pushButton_setting_5.setIconSize(QtCore.QSize(72, 72))
        self.pushButton_setting_5.setObjectName("pushButton_setting_5")
        
        self.pushButton_setting_6 = QtWidgets.QPushButton(self.frame_9)
        self.pushButton_setting_6.setGeometry(QtCore.QRect(130, 30, 81, 81))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_setting_6.setFont(font)
        self.pushButton_setting_6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_setting_6.setStyleSheet("border-width: 6px;\n"
"border-style: solid;\n"
"border-radius: 40px;\n"
"border-color: black")
        self.pushButton_setting_6.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap("photos/sfdf.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting_6.setIcon(icon5)
        self.pushButton_setting_6.setIconSize(QtCore.QSize(72, 72))
        self.pushButton_setting_6.setObjectName("pushButton_setting_6")

        self.label_27 = QtWidgets.QLabel(self.frame_9)
        self.label_27.setGeometry(QtCore.QRect(20, 0, 201, 31))
        self.label_27.setStyleSheet("")
        self.label_27.setObjectName("label_27")

        
        self.frame_10 = QtWidgets.QFrame(Form)
        self.frame_10.setGeometry(QtCore.QRect(850, 820, 271, 51))
        self.frame_10.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        
        self.label_24 = QtWidgets.QLabel(self.frame_10)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 111, 31))
        self.label_24.setStyleSheet("")
        self.label_24.setObjectName("label_24")
        
        self.comboBox_4 = QtWidgets.QComboBox(self.frame_10)
        self.comboBox_4.setGeometry(QtCore.QRect(180, 10, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.comboBox_4.setFont(font)
        self.comboBox_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.comboBox_4.setStyleSheet("color: white;\n"
"border-width: 2px;\n"
"border-style: solid;\n"
"border-color:  rgb(0, 0, 113);\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 113);")
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        
        self.lineEdit_4 = QtWidgets.QLineEdit(self.frame_10)
        self.lineEdit_4.setGeometry(QtCore.QRect(110, 10, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(17)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 50);\n"
"border-width: 1px;\n"
"border-style: solid;\n"
"border-color:  rgb(0, 0, 50);\n"
"")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.lineEdit_4.setValidator(QtGui.QDoubleValidator())

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)



        # button command
        self.pushButton_start.clicked.connect(self.calculate)
        # self.pushButton_start.clicked.connect(self.speedDisplay)
        # self.pushButton_start.clicked.connect(self.realTime)


        self.pushButton_stop.clicked.connect(self.realEnd)

        self.pushButton_speed_2.clicked.connect(self.speedUp)
        self.pushButton_speed_1.clicked.connect(self.speedDown)

        self.pushButton_setting_5.clicked.connect(self.male)
        self.pushButton_setting_6.clicked.connect(self.female)

        self.pushButton_setting_4.clicked.connect(self.song)
        self.pushButton_setting_7.clicked.connect(self.next)
        self.pushButton_setting_3.clicked.connect(self.previous)

        self.pushButton_setting_2.clicked.connect(self.mini)

        self.pushButton_exit.clicked.connect(self.exit)
        # button command



        self.playlist = QtMultimedia.QMediaPlaylist()
        self.player = QtMultimedia.QMediaPlayer()
        self.playlist.addMedia(QtMultimedia.QMediaContent(QtCore.QUrl.fromLocalFile("songs/song0.mp3")))
        self.playlist.addMedia(QtMultimedia.QMediaContent(QtCore.QUrl.fromLocalFile("songs/song1.mp3")))
        self.playlist.addMedia(QtMultimedia.QMediaContent(QtCore.QUrl.fromLocalFile("songs/song2.mp3")))
        self.playlist.addMedia(QtMultimedia.QMediaContent(QtCore.QUrl.fromLocalFile("songs/song3.mp3")))
        self.playlist.addMedia(QtMultimedia.QMediaContent(QtCore.QUrl.fromLocalFile("songs/song4.mp3")))
        self.playlist.addMedia(QtMultimedia.QMediaContent(QtCore.QUrl.fromLocalFile("songs/song5.mp3")))
        self.playlist.addMedia(QtMultimedia.QMediaContent(QtCore.QUrl.fromLocalFile("songs/song6.mp3")))
        self.player.setPlaylist(self.playlist)



        timer = QTimer(self)
        timer.timeout.connect(self.showTime)
        timer.start(1000)

        timer = QTimer(self)
        timer.timeout.connect(self.realDisplay)
        timer.start(1000)



    # RPM = 0
    radius = 0.0 # meter
    weight = 0.0 # kg
    height = 0.0 # meter
    goal = 0.0 # meter
    speed = 0.0
    gender = ""
    calories = 0.0

    second = 0
    minute = 0
    hour = 0

    run = False
    system = False
    play = False

    # speed = (2 * 3.14 * radius * RPM * 3.6) / 60 # km/h "must change"
    DistancePersecond = speed / 3600 # km
    # numOfStep = 2 * (( 5280 / ( height * 0.413 * 39.37 / 12 ) ) * ( Distance / 1609.344 ))
    # CaloriesBurntPerSecond  = (( 0.035 * weight ) + (( (speed/3.6)**2 / height ) * 0.029 * weight )) * 1 / 60
    CaloriesBurntPerSecond = 0.0



    def calculate(self):
        error = []

        in_height = self.lineEdit.text()
        if in_height == "" or float(in_height) == 0.0 :
        	error.append("height")
        else:
        	height = float(in_height)
        	height_type = self.comboBox.currentText()
        	if height_type == "m":
        		self.height = height
        	elif height_type == "inch":
        		self.height = height / 39.37


        in_weight = self.lineEdit_2.text()
        if in_weight == "" or float(in_weight) == 0.0 :
        	error.append("weight")
        else:
        	weight = float(in_weight)
        	weight_type = self.comboBox_2.currentText()
        	if weight_type == "kg":
        	    self.weight = weight            
        	elif weight_type == "lb":
        	    self.weight = weight / 2.205


        radius = float(self.lineEdit_4.text())
        radius_type = self.comboBox_4.currentText()
        if radius_type == "cm":
            self.radius = radius / 100            
        elif radius_type == "mm":
            self.radius = radius / 1000
        elif radius_type == "default":
            self.radius = 0.08


        in_goal = self.lineEdit_3.text()
        if in_goal == "" or float(in_goal) == 0.0 :
        	error.append("goal")
        else:
        	goal = float(in_goal)
        	goal_type = self.comboBox_3.currentText()
        	if goal_type == "m":
        	    self.goal = goal            
        	elif goal_type == "km":
        	    self.goal = goal * 1000
        	elif goal_type == "mil":
        	    self.goal = goal * 1609.34


        if "height" in  error :
            self.massage("Please Enter your Height")
            
        elif "weight" in error :
            self.massage("Please Enter your Weight")
            
        elif "goal" in error :
            self.massage("Please Enter your Goal for today")

        elif self.gender == "" :
            self.massage("Please select your Gender")

        elif self.speed == 0.0 :
            self.massage("Please choose speed")

        else:
            # self.CaloriesBurntPerSecond  = (( 0.035 * self.weight ) + (( (self.speed/3.6)**2 / self.height ) * 0.029 * self.weight )) * 1 / 60

            self.pushButton_setting_6.setEnabled(False)
            self.pushButton_setting_5.setEnabled(False)
            self.lineEdit.setEnabled(False)
            self.lineEdit_2.setEnabled(False)
            self.lineEdit_3.setEnabled(False)
            self.lineEdit_4.setEnabled(False)
            self.speedDisplay()
            self.realTime()



        print(self.height)
        print(self.weight)
        print(self.radius)
        print(self.goal)
        print(self.gender)


    def show(self):
    	msg = QMessageBox()
    	msg.setWindowTitle("Treadmil")
    	msg.setText("main text")
    	x = msg.exec_()


    def exit(self):
        Form.close()


    def realEnd(self):
        self.run = False
        self.pushButton_start.setText("START")

        self.label_steps.setText("0")
        self.label_steps.setStyleSheet("color: white;")

        self.label_distance.setText("0.000")
        self.label_distance.setStyleSheet("color: white;")

        self.label_calories.setText("0.0")
        self.label_calories.setStyleSheet("color: white;")

        self.label_time.setText("00:00:00")
        self.label_time.setStyleSheet("color: white;")

        self.progressBar.setValue(0)

        self.label_3.setPixmap(QtGui.QPixmap("photos/source (1).gif"))

        self.pushButton_setting_6.setEnabled(True)
        self.pushButton_setting_6.setStyleSheet("border-width: 6px;\n" "border-style: solid;\n" "border-radius: 40px;\n" "border-color: black")
        self.pushButton_setting_5.setStyleSheet("border-width: 6px;\n" "border-style: solid;\n" "border-radius: 40px;\n" "border-color: black;\n" "\n" "")
        self.pushButton_setting_5.setEnabled(True)

        self.lineEdit.setEnabled(True)
        self.lineEdit_2.setEnabled(True)
        self.lineEdit_3.setEnabled(True)
        self.lineEdit_4.setEnabled(True)

        self.second = 0
        self.minute = 0
        self.hour = 0
        self.calories = 0.0
        self.gender = ""
        self.DistancePersecond = self.speed / 3600
        self.run = False
        self.system = False


    def realTime(self):
        print("clicked")

        if self.gender == "male" :
            self.movie = QtGui.QMovie("photos/source (1).gif")
            self.label_3.setMovie(self.movie)
            self.movie.start()
        elif self.gender == "female" :
            self.movie = QtGui.QMovie("photos/source.gif")
            self.label_3.setMovie(self.movie)
            self.movie.start()

        self.pushButton_start.setText("STOP")
        if self.system :
            self.pushButton_start.setText("RESUME")
            self.system = False
            self.run = False

            if self.gender == "male" :
                self.label_3.setPixmap(QtGui.QPixmap("photos/source (1).gif"))
            else:
                self.label_3.setPixmap(QtGui.QPixmap("photos/source.gif"))
        else:
            self.system = True
            self.run = True 


    def realDisplay(self):
        if self.run :
            self.DistancePersecond = self.DistancePersecond + (self.speed / 3600 )
            self.CaloriesBurntPerSecond  = (( 0.035 * self.weight ) + (( (self.speed/3.6)**2 / self.height ) * 0.029 * self.weight )) * 1 / 60
            self.calories = self.calories + self.CaloriesBurntPerSecond
   
            self.second = self.second + 1
            if self.second >= 59 :
                self.minute = self.minute + 1
                self.second = 0
                if self.minute >= 59 :
                    self.hour = self.hour + 1
                    self.minute = 0


            time = "{:02d}".format(self.hour) + ":" + "{:02d}".format(self.minute) + ":" + "{:02d}".format(self.second)
            self.label_time.setStyleSheet("color: white;")
            self.label_time.setText(time)

            self.label_distance.setText("{:.3f}".format(self.DistancePersecond))
            self.label_distance.setStyleSheet("color: white;")

            self.label_calories.setText("{:.1f}".format(self.calories))
            self.label_calories.setStyleSheet("color: white;")

            numStep = 2 * (( 5280 / ( self.height * 0.413 * 39.37 / 12 ) ) * ( self.DistancePersecond / 1.609344 ))
            self.label_steps.setText("{:.0f}".format(numStep))
            self.label_steps.setStyleSheet("color: white;")

            self.progressBar.setValue(int(self.DistancePersecond * 1000 * 100 / self.goal))


    def speedDisplay(self):
        speedOneDesci = "{:.2f}".format(self.speed)
        self.label_speed.setStyleSheet("color: white;")
        self.label_speed.setText(speedOneDesci)


    def speedDown(self):
        currentSpeed = "{:.1f}".format(self.speed)
        newSpeed = float(currentSpeed) - 0.1
        self.speed = newSpeed
        self.label_speed.setStyleSheet("color: white;")
        self.label_speed.setText(str(newSpeed))


    def speedUp(self,num):
        currentSpeed = "{:.1f}".format(self.speed)
        newSpeed = float(currentSpeed) + 0.1
        self.speed = newSpeed
        self.label_speed.setStyleSheet("color: white;")
        self.label_speed.setText(str(newSpeed))


    def showTime(self):
        currentTime = QTime.currentTime()
        displayTime = currentTime.toString(Qt.DefaultLocaleLongDate)
        self.label_13.setText(displayTime)
        currentDate = QDate.currentDate()
        self.label_12.setText(currentDate.toString(Qt.DefaultLocaleLongDate))    


    def mini(self):
        Form.showMinimized()


    def male(self):
        self.gender = "male"
        self.label_3.setPixmap(QtGui.QPixmap("photos/source (1).gif"))
        self.pushButton_setting_6.setStyleSheet("border-width: 6px;\n" "border-style: solid;\n" "border-radius: 40px;\n" "border-color: black")
        self.pushButton_setting_5.setStyleSheet("border-width: 6px;\n" "border-style: solid;\n" "border-radius: 40px;\n" "border-color: rgb(0, 0, 255);\n" "\n" "")


    def female(self):
        self.gender = "female"
        self.label_3.setPixmap(QtGui.QPixmap("photos/source.gif"))
        self.pushButton_setting_6.setStyleSheet("border-width: 6px;\n" "border-style: solid;\n" "border-radius: 40px;\n" "border-color: rgb(155, 0, 91)")
        self.pushButton_setting_5.setStyleSheet("border-width: 6px;\n" "border-style: solid;\n" "border-radius: 40px;\n" "border-color: black;\n" "\n" "")


    def massage(self, massage):
        msg = QMessageBox()
        msg.setText(massage)
        msg.setWindowTitle("Enter Data")
        msg.setWindowIcon(QtGui.QIcon("black tic.png"))
        msg.setIcon(QMessageBox.Information)
        msg.setStyleSheet("color: red;")
        msg.exec_()


    def song(self):
        if not self.play :
            # song = QFileDialog.getOpenFileName(self, "songs", "~", "Sound Files (*.mp3 *.ogg *.wav *.m4a)")
            # self.player = QtMultimedia.QMediaPlayer()
            # self.playlist.addMedia(QtMultimedia.QMediaContent(QtCore.QUrl.fromLocalFile("songs")))
            # self.player.setPlaylist(self.playlist)

            self.player.play()

            icon3 = QtGui.QIcon()
            icon3.addPixmap(QtGui.QPixmap("photos/video-player3.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.pushButton_setting_4.setIcon(icon3)

            self.play = True


        elif self.play :
            self.player.pause()

            icon3 = QtGui.QIcon()
            icon3.addPixmap(QtGui.QPixmap("photos/video-player.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
            self.pushButton_setting_4.setIcon(icon3)

            self.play = False


    def next(self):
        self.player.playlist().next()


    def previous(self):
        self.player.playlist().previous()




    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_time.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">00:00:00</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">SESSION TIME</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">CALORIES</span></p></body></html>"))
        self.label_calories.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">0.0</span></p></body></html>"))
        self.label_distance.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">0.000</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">DISTANCE</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; color:#ffffff;\">km</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; color:#ffffff;\">km/h</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">SPEED</span></p></body></html>"))
        self.label_speed.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">0.00</span></p></body></html>"))
        self.pushButton_speed_2.setText(_translate("Form", ">"))
        self.pushButton_speed_1.setText(_translate("Form", "<"))
        self.pushButton_start.setText(_translate("Form", "START"))
        self.pushButton_stop.setText(_translate("Form", "RESET"))
        self.label_12.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Wednesday, Desember 8, 2020</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">12:17:03 AM</span></p></body></html>"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">NUMBER OF STEPS</span></p></body></html>"))
        self.label_steps.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>"))
        self.label_16.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">HEIGHT</span></p></body></html>"))
        self.lineEdit.setText(_translate("Form", ""))
        self.comboBox.setItemText(0, _translate("Form", "m"))
        self.comboBox.setItemText(1, _translate("Form", "inch"))
        self.label_17.setText(_translate("Form", "<html><head/><body><p align=\"center\">___________________</p></body></html>"))
        self.label_18.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">WEIGHT</span></p></body></html>"))
        self.lineEdit_2.setText(_translate("Form", ""))
        self.comboBox_2.setItemText(0, _translate("Form", "kg"))
        self.comboBox_2.setItemText(1, _translate("Form", "lb"))
        self.label_19.setText(_translate("Form", "<html><head/><body><p align=\"center\">____________________</p></body></html>"))
        self.label_21.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">TARGET</span></p></body></html>"))
        self.comboBox_3.setItemText(0, _translate("Form", "m"))
        self.comboBox_3.setItemText(1, _translate("Form", "km"))
        self.comboBox_3.setItemText(2, _translate("Form", "mil"))
        self.label_22.setText(_translate("Form", "<html><head/><body><p align=\"center\">___________________</p></body></html>"))
        self.lineEdit_3.setText(_translate("Form", ""))
        self.label_24.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">RADIUS -</span></p></body></html>"))
        self.comboBox_4.setItemText(0, _translate("Form", "default"))
        self.comboBox_4.setItemText(1, _translate("Form", "cm"))
        self.comboBox_4.setItemText(2, _translate("Form", "mm"))
        self.lineEdit_4.setText(_translate("Form", "8"))
        self.label_27.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">GENDER</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
