# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QTimer, QTime, QDate,Qt
import sys


class Ui_Form(object):

    def __init__(self, message):
        print(message)



    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1146, 739)
        Form.setWindowFlag(Qt.FramelessWindowHint)

        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())

        Form.setSizePolicy(sizePolicy)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.011, stop:0.0227273 rgba(0, 0, 28, 255), stop:0.977273 rgba(0, 0, 39, 255))")
        
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(870, 220, 241, 161))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.label_time = QtWidgets.QLabel(self.frame)
        self.label_time.setGeometry(QtCore.QRect(50, 80, 151, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        self.label_time.setFont(font)
        self.label_time.setObjectName("label_time")
        
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 30, 31, 41))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("photos/79-795942_or-tool-svg-png-icon-free-download-clock.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(60, 30, 181, 41))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(870, 440, 241, 161))
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(40, 20, 41, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("photos/Calories_Burned_-fire-Calories_Burn-Burn-Metabolism-512.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(90, 20, 111, 41))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        
        self.label_calories = QtWidgets.QLabel(self.frame_2)
        self.label_calories.setGeometry(QtCore.QRect(80, 70, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(48)
        self.label_calories.setFont(font)
        self.label_calories.setObjectName("label_calories")
        
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(40, 390, 371, 141))
        self.frame_3.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        
        self.label_distance = QtWidgets.QLabel(self.frame_3)
        self.label_distance.setGeometry(QtCore.QRect(190, 60, 101, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        font.setBold(False)
        font.setWeight(50)
        self.label_distance.setFont(font)
        self.label_distance.setTextFormat(QtCore.Qt.RichText)
        self.label_distance.setObjectName("label_distance")
        
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 191, 141))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("photos/road-icon-on-white-background-vector-21154187.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(220, 20, 111, 41))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(290, 60, 61, 51))
        self.label_10.setObjectName("label_10")
        
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(40, 570, 371, 131))
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(100, 20, 71, 41))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("photos/600-6003521_ketond-keto-supplements-com-agility-icon-png-transparent.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(180, 70, 91, 51))
        self.label_6.setObjectName("label_6")
        
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(170, 20, 91, 41))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        
        self.label_speed = QtWidgets.QLabel(self.frame_4)
        self.label_speed.setGeometry(QtCore.QRect(100, 70, 81, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        self.label_speed.setFont(font)
        self.label_speed.setTextFormat(QtCore.Qt.RichText)
        self.label_speed.setObjectName("label_speed")
        
        self.pushButton_speed_2 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_speed_2.setGeometry(QtCore.QRect(290, 70, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_speed_2.setFont(font)
        self.pushButton_speed_2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_speed_2.setStyleSheet("color: rgb(255, 255, 0);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(255, 255, 0);\n"
"border-radius: 25px;")
        self.pushButton_speed_2.setObjectName("pushButton_speed_2")
        
        self.pushButton_speed_1 = QtWidgets.QPushButton(self.frame_4)
        self.pushButton_speed_1.setGeometry(QtCore.QRect(20, 70, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_speed_1.setFont(font)
        self.pushButton_speed_1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_speed_1.setStyleSheet("color: rgb(255, 255, 0);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(255, 255, 0);\n"
"border-radius: 25px;")
        self.pushButton_speed_1.setObjectName("pushButton_speed_1")
        
        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(690, 650, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_start.setStyleSheet("color: white;\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: red;\n"
"border-radius: 20px;")
        self.pushButton_start.setObjectName("pushButton_start")
        
        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setGeometry(QtCore.QRect(910, 650, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop.setStyleSheet("color: white;\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color:rgb(255, 255, 0) ;\n"
"border-radius: 20px;")
        self.pushButton_stop.setObjectName("pushButton_stop")
        
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(450, 200, 381, 421))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setPixmap(QtGui.QPixmap("photos/source (1).gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(40, 20, 191, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet("color: white;")
        self.label_12.setTextFormat(QtCore.Qt.RichText)
        self.label_12.setObjectName("label_12")
        
        self.pushButton_setting = QtWidgets.QPushButton(Form)
        self.pushButton_setting.setGeometry(QtCore.QRect(980, 30, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_setting.setFont(font)
        self.pushButton_setting.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_setting.setStyleSheet("color: rgb(255, 255, 0);\n"
"border-width: 4px;\n"
"border-style: solid;\n"
"border-color: rgb(255, 110, 31);\n"
"border-radius: 25px;")
        self.pushButton_setting.setText("")
        
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("photos/settings-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting.setIcon(icon)
        self.pushButton_setting.setIconSize(QtCore.QSize(48, 48))
        self.pushButton_setting.setObjectName("pushButton_setting")
        
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(60, 50, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(20)
        font.setBold(False)
        font.setWeight(50)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: white;")
        self.label_13.setObjectName("label_13")
        
        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setGeometry(QtCore.QRect(470, 650, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_add.setStyleSheet("color: white;\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(85, 0, 255);\n"
"border-radius: 20px;")
        self.pushButton_add.setObjectName("pushButton_add")
        
        self.frame_5 = QtWidgets.QFrame(Form)
        self.frame_5.setGeometry(QtCore.QRect(40, 200, 371, 151))
        self.frame_5.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(140, 10, 201, 41))
        self.label_14.setStyleSheet("")
        self.label_14.setObjectName("label_14")
        
        self.label_steps = QtWidgets.QLabel(self.frame_5)
        self.label_steps.setGeometry(QtCore.QRect(200, 50, 111, 71))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(48)
        font.setBold(False)
        font.setWeight(50)
        self.label_steps.setFont(font)
        self.label_steps.setObjectName("label_steps")
        
        self.label_23 = QtWidgets.QLabel(self.frame_5)
        self.label_23.setGeometry(QtCore.QRect(20, 20, 111, 111))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("photos/feet-clipart-blue-foot-foot-icon-png-transparent.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        
        self.progressBar = QtWidgets.QProgressBar(Form)
        self.progressBar.setGeometry(QtCore.QRect(40, 120, 1071, 51))
        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(28)
        self.progressBar.setFont(font)
        self.progressBar.setAutoFillBackground(False)
        self.progressBar.setStyleSheet("color: white;\n"
"background-color: rgb(0, 0, 50);\n"
"border: 3px solid ;\n"
"border-color: rgb(0, 0, 50)")
        self.progressBar.setProperty("value", 100)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setObjectName("progressBar")
        
        self.pushButton_exit = QtWidgets.QPushButton(Form)
        self.pushButton_exit.setGeometry(QtCore.QRect(1050, 30, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_exit.setFont(font)
        self.pushButton_exit.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_exit.setStyleSheet("color: rgb(255, 255, 0);\n"
"border-width: 4px;\n"
"border-style: solid;\n"
"border-color:rgb(255, 0, 0);\n"
"border-radius: 25px;")
        self.pushButton_exit.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("photos/kisspng-computer-icons-shutdown-internet-computer-software-quit-5ad8d713227452.1198148915241602751411.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_exit.setIcon(icon1)
        self.pushButton_exit.setIconSize(QtCore.QSize(63, 68))
        self.pushButton_exit.setObjectName("pushButton_exit")
        
        self.pushButton_setting_3 = QtWidgets.QPushButton(Form)
        self.pushButton_setting_3.setGeometry(QtCore.QRect(500, 20, 71, 71))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_setting_3.setFont(font)
        self.pushButton_setting_3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_setting_3.setStyleSheet("border-width: 3px;\n"
"border-style: solid;\n"
"border-radius: 35px;")
        self.pushButton_setting_3.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("photos/189639.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting_3.setIcon(icon2)
        self.pushButton_setting_3.setIconSize(QtCore.QSize(70, 70))
        self.pushButton_setting_3.setObjectName("pushButton_setting_3")
        
        self.pushButton_setting_4 = QtWidgets.QPushButton(Form)
        self.pushButton_setting_4.setGeometry(QtCore.QRect(590, 20, 71, 71))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_setting_4.setFont(font)
        self.pushButton_setting_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_setting_4.setStyleSheet("border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(255, 0, 0);\n"
"border-radius: 35px;")
        self.pushButton_setting_4.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("photos/istockphoto-896772616-170667a.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_setting_4.setIcon(icon3)
        self.pushButton_setting_4.setIconSize(QtCore.QSize(75, 74))
        self.pushButton_setting_4.setObjectName("pushButton_setting_4")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)


        # button command
        # self.pushButton_add.clicked.connect(self.openWindows)
        # self.pushButton_start.clicked.connect(self.speedDisplay)
        # self.pushButton_start.clicked.connect(self.realTime)

        # self.pushButton_stop.clicked.connect(self.realEnd)

        # self.pushButton_speed_2.clicked.connect(self.speedUp)
        # self.pushButton_speed_1.clicked.connect(self.speedDown)

        self.pushButton_exit.clicked.connect(self.exit)
        self.pushButton_add.clicked.connect(self.add)
        # button command

    def input(self, massage):
        print(massage)

    def exit(self):
        exit()

    def add(self):
        print(self.Ui_MainWindow.height)


    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_time.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">00:00:00</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">SESSION TIME</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">CALORIES</span></p></body></html>"))
        self.label_calories.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">0.0</span></p></body></html>"))
        self.label_distance.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">0.000</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">DISTANCE</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; color:#ffffff;\">km</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; color:#ffffff;\">km/h</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">SPEED</span></p></body></html>"))
        self.label_speed.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">0.00</span></p></body></html>"))
        self.pushButton_speed_2.setText(_translate("Form", ">"))
        self.pushButton_speed_1.setText(_translate("Form", "<"))
        self.pushButton_start.setText(_translate("Form", "START"))
        self.pushButton_stop.setText(_translate("Form", "RESET"))
        self.label_12.setText(_translate("Form", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Microsoft YaHei UI\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\';\">Wednesday, Desember 8, 2020</span></p></body></html>"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">12:17:03 AM</span></p></body></html>"))
        self.pushButton_add.setText(_translate("Form", "ADD"))
        self.label_14.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">NUMBER OF STEPS</span></p></body></html>"))
        self.label_steps.setText(_translate("Form", "<html><head/><body><p><span style=\" color:#ffffff;\">0</span></p></body></html>"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
