# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import sys
import time
from PyQt5.QtCore import QTimer, QTime, QDate,Qt


class Ui_Form(QtWidgets.QWidget, QtCore.QTimer):


	


    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.WindowModal)
        Form.resize(1109, 658)
        
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        Form.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        Form.setAutoFillBackground(False)
        Form.setStyleSheet("background-color:qlineargradient(spread:reflect, x1:0, y1:0, x2:1, y2:0.011, stop:0.0227273 rgba(0, 0, 28, 255), stop:0.977273 rgba(0, 0, 39, 255))")
        
      # frame setup  
        self.frame = QtWidgets.QFrame(Form)
        self.frame.setGeometry(QtCore.QRect(840, 290, 241, 141))
        self.frame.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        
        self.label_time = QtWidgets.QLabel(self.frame)
        self.label_time.setGeometry(QtCore.QRect(40, 70, 161, 51))
        self.label_time.setObjectName("label_time")
        
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 20, 31, 41))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("../../../Downloads/79-795942_or-tool-svg-png-icon-free-download-clock.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_7 = QtWidgets.QLabel(self.frame)
        self.label_7.setGeometry(QtCore.QRect(60, 20, 181, 41))
        self.label_7.setStyleSheet("")
        self.label_7.setObjectName("label_7")
        
      # frame_2 setup  
        self.frame_2 = QtWidgets.QFrame(Form)
        self.frame_2.setGeometry(QtCore.QRect(880, 460, 201, 141))
        self.frame_2.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        
        self.label = QtWidgets.QLabel(self.frame_2)
        self.label.setGeometry(QtCore.QRect(20, 20, 41, 41))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("../../../Downloads/Calories_Burned_-fire-Calories_Burn-Burn-Metabolism-512.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(70, 20, 111, 41))
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        
        self.label_calories = QtWidgets.QLabel(self.frame_2)
        self.label_calories.setGeometry(QtCore.QRect(30, 60, 161, 91))
        self.label_calories.setObjectName("label_calories")
        
      # frame_3 setup  
        self.frame_3 = QtWidgets.QFrame(Form)
        self.frame_3.setGeometry(QtCore.QRect(40, 290, 371, 141))
        self.frame_3.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        
        self.label_distance = QtWidgets.QLabel(self.frame_3)
        self.label_distance.setGeometry(QtCore.QRect(190, 60, 91, 51))
        self.label_distance.setObjectName("label_distance")
        
        self.label_11 = QtWidgets.QLabel(self.frame_3)
        self.label_11.setGeometry(QtCore.QRect(0, 0, 191, 141))
        self.label_11.setText("")
        self.label_11.setPixmap(QtGui.QPixmap("../../../Downloads/road-icon-on-white-background-vector-21154187.png"))
        self.label_11.setScaledContents(True)
        self.label_11.setObjectName("label_11")
        self.label_8 = QtWidgets.QLabel(self.frame_3)
        self.label_8.setGeometry(QtCore.QRect(220, 30, 111, 41))
        self.label_8.setStyleSheet("")
        self.label_8.setObjectName("label_8")
        self.label_10 = QtWidgets.QLabel(self.frame_3)
        self.label_10.setGeometry(QtCore.QRect(290, 60, 61, 51))
        self.label_10.setObjectName("label_10")
        
      # frame_4 setup  
        self.frame_4 = QtWidgets.QFrame(Form)
        self.frame_4.setGeometry(QtCore.QRect(110, 480, 181, 131))
        self.frame_4.setStyleSheet("background-color: rgb(0, 0, 50)")
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        
        self.label_9 = QtWidgets.QLabel(self.frame_4)
        self.label_9.setGeometry(QtCore.QRect(10, 10, 71, 41))
        self.label_9.setText("")
        self.label_9.setPixmap(QtGui.QPixmap("../../../Downloads/600-6003521_ketond-keto-supplements-com-agility-icon-png-transparent.png"))
        self.label_9.setScaledContents(True)
        self.label_9.setObjectName("label_9")
        self.label_6 = QtWidgets.QLabel(self.frame_4)
        self.label_6.setGeometry(QtCore.QRect(80, 70, 91, 51))
        self.label_6.setObjectName("label_6")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(80, 10, 91, 41))
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        
        self.label_speed = QtWidgets.QLabel(self.frame_4)
        self.label_speed.setGeometry(QtCore.QRect(10, 70, 71, 51))
        self.label_speed.setObjectName("label_speed")
        


        self.pushButton_start = QtWidgets.QPushButton(Form)
        self.pushButton_start.setGeometry(QtCore.QRect(430, 550, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.pushButton_start.setFont(font)
        self.pushButton_start.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_start.setStyleSheet("color: white;\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: red;\n"
"border-radius: 20px;")
        self.pushButton_start.setObjectName("pushButton_start")
        

        self.pushButton_stop = QtWidgets.QPushButton(Form)
        self.pushButton_stop.setGeometry(QtCore.QRect(650, 550, 191, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.pushButton_stop.setFont(font)
        self.pushButton_stop.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_stop.setStyleSheet("color: white;\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(85, 0, 255);\n"
"border-radius: 20px;")
        self.pushButton_stop.setObjectName("pushButton_stop")
        

        self.pushButton_speed_1 = QtWidgets.QPushButton(Form)
        self.pushButton_speed_1.setGeometry(QtCore.QRect(50, 560, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_speed_1.setFont(font)
        self.pushButton_speed_1.setStyleSheet("color: rgb(255, 255, 0);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(255, 255, 0);\n"
"border-radius: 25px;")
        self.pushButton_speed_1.setObjectName("pushButton_speed_1")
        

        self.pushButton_speed_2 = QtWidgets.QPushButton(Form)
        self.pushButton_speed_2.setGeometry(QtCore.QRect(300, 560, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_speed_2.setFont(font)
        self.pushButton_speed_2.setStyleSheet("color: rgb(255, 255, 0);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(255, 255, 0);\n"
"border-radius: 25px;")
        self.pushButton_speed_2.setObjectName("pushButton_speed_2")
        

        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(460, 100, 321, 421))
        self.label_3.setStyleSheet("")
        self.label_3.setText("")
        self.label_3.setTextFormat(QtCore.Qt.PlainText)
        self.label_3.setPixmap(QtGui.QPixmap("../../../Downloads/man-running.gif"))
        self.label_3.setScaledContents(True)
        self.label_3.setObjectName("label_3")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(20, 20, 191, 31))
        self.label_12.setStyleSheet("color: white;")
        self.label_12.setObjectName("label_12")
        

        self.pushButton_speed_3 = QtWidgets.QPushButton(Form)
        self.pushButton_speed_3.setGeometry(QtCore.QRect(1030, 20, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_speed_3.setFont(font)
        self.pushButton_speed_3.setStyleSheet("color: rgb(255, 255, 0);\n""border-width: 3px;\n""border-style: solid;\n""border-color: rgb(255, 255, 0);\n""border-radius: 25px;")
        self.pushButton_speed_3.setObjectName("pushButton_speed_3")
        

        self.pushButton_speed_4 = QtWidgets.QPushButton(Form)
        self.pushButton_speed_4.setGeometry(QtCore.QRect(960, 20, 51, 51))
        font = QtGui.QFont()
        font.setFamily("MS PGothic")
        font.setPointSize(28)
        self.pushButton_speed_4.setFont(font)
        self.pushButton_speed_4.setStyleSheet("color: rgb(255, 255, 0);\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: rgb(255, 255, 0);\n"
"border-radius: 25px;")
        self.pushButton_speed_4.setObjectName("pushButton_speed_4")
        

        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(30, 50, 161, 31))
        self.label_13.setStyleSheet("color: white;")
        self.label_13.setObjectName("label_13")
        self.label_23 = QtWidgets.QLabel(Form)
        self.label_23.setGeometry(QtCore.QRect(110, 160, 61, 61))
        self.label_23.setText("")
        self.label_23.setPixmap(QtGui.QPixmap("../../../Downloads/feet-clipart-blue-foot-foot-icon-png-transparent.png"))
        self.label_23.setScaledContents(True)
        self.label_23.setObjectName("label_23")
        

        self.pushButton_add = QtWidgets.QPushButton(Form)
        self.pushButton_add.setGeometry(QtCore.QRect(230, 100, 151, 61))
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.pushButton_add.setFont(font)
        self.pushButton_add.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_add.setStyleSheet("color: white;\n"
"border-width: 3px;\n"
"border-style: solid;\n"
"border-color: red;\n"
"border-radius: 20px;")
        self.pushButton_add.setObjectName("pushButton_add")

      
        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

        self.pushButton_stop.clicked.connect(self.startup2)

        self.pushButton_start.clicked.connect(self.startup)

# time setup
        timer = QTimer(self)
        timer.timeout.connect(self.showTime)
        timer.start(1000)

    hour = 0
    minutes = 0
    second = 0

    def stopwatch(self):
    	time = self.second
    	time = time + 1
    	self.second = time
    	print(time)
    	# currentTime = QTime.currentTime()
    	# tim = currentTime.toString('hh:mm:ss')
    	# print(tim)
    	# print(self.dis)
    def startup2(self):
    	timer = QTimer(self)
    	timer.timeout.connect(self.stopwatch)
    	timer.start(1000)


    def startup(self):
    	timer = QTimer(self)
    	timer.timeout.connect(self.distance)
    	timer.start(1000)

    def distance(self):
    	currentTime = QTime.currentTime()
    	displayTxt = currentTime.toString(Qt.DefaultLocaleLongDate)
    	doc = QtGui.QTextDocument()
    	doc.setHtml(self.label_distance.text())
    	start = doc.toPlainText()
    	print(start)
    	num = int(start)
    	num = num + 1
    	font = QtGui.QFont()
    	font.setFamily("MS UI Gothic")
    	font.setPointSize(20)
    	self.label_distance.setFont(font)
    	self.label_distance.setStyleSheet("color: white;")
    	self.label_distance.setText(str(num))



    def showTime(self):
        currentTime = QTime.currentTime()
        displayTxt = currentTime.toString(Qt.DefaultLocaleLongDate)
        # print(displayTxt)
        currentDate = QDate.currentDate()
        displayDat = currentDate.toString(Qt.DefaultLocaleLongDate)
        # print(displayDat)
        font = QtGui.QFont()
        font.setFamily("MS UI Gothic")
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setText(displayTxt)
        self.label_13.setStyleSheet("color: white;")

        font = QtGui.QFont()
        font.setFamily("Microsoft YaHei UI")
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setText(displayDat)
        self.label_12.setStyleSheet("color: white;")# time setup
        

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_time.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; color:#ffffff;\">0:25:30</span></p></body></html>"))
        self.label_7.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">SESSION TIME</span></p></body></html>"))
        self.label_2.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">CALORIES</span></p></body></html>"))
        self.label_calories.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; color:#ffffff;\">125</span></p></body></html>"))
        self.label_distance.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; color:#ffffff;\">0</span></p></body></html>"))
        self.label_8.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">DISTANCE</span></p></body></html>"))
        self.label_10.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; color:#ffffff;\">km</span></p></body></html>"))
        self.label_6.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:28pt; color:#ffffff;\">km/h</span></p></body></html>"))
        self.label_4.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt; font-weight:600; color:#ffffff;\">SPEED</span></p></body></html>"))
        self.label_speed.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt; color:#ffffff;\">5.3</span></p></body></html>"))
        self.pushButton_start.setText(_translate("Form", "START"))
        self.pushButton_stop.setText(_translate("Form", "RESET"))
        self.pushButton_speed_1.setText(_translate("Form", "<"))
        self.pushButton_speed_2.setText(_translate("Form", ">"))
        self.label_12.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Wednesday, Desember 8, 2020</span></p></body></html>"))
        self.pushButton_speed_3.setText(_translate("Form", ">"))
        self.pushButton_speed_4.setText(_translate("Form", ">"))
        self.label_13.setText(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">00:00:00</span></p></body></html>"))
        self.pushButton_add.setText(_translate("Form", "ADD"))





if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
